# Site settings
# Enter your own credentials here
title: "Research-Blog"
email: mahdir@gatech.edu
       jcm3@gatech.edu
description: >
  Quantifying Hydraulic Tortuosity in Randomly Packed Binary-sized Structures
baseurl: "/MIC-Packed-Particles" # replace ``/research-pages`` with the name of the parents repository
url: "Mahdi-Roozbahani.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: twitterhandle
disqus: mahdiroozbahani

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: Mahdi-Roozbahani
  repo: MIC-Packed-Particles
  # Branch hosting Github pages
  branch: gh-pages
